// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/common/echarts/BarChart.vue')['default']
    NaiveProvider: typeof import('./src/components/common/NaiveProvider.vue')['default']
    PieChart: typeof import('./src/components/common/echarts/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
